"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestSeasidePlotlyExamples,
	#superclass : #PackageManifest,
	#category : #'Seaside-Plotly-Examples-Manifest'
}

{ #category : #'code-critics' }
ManifestSeasidePlotlyExamples class >> ruleGRUsesCurlyBraceArraysRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'Seaside-Plotly-Examples')) #'2021-11-02T17:27:53.843189-03:00') )
]

{ #category : #'code-critics' }
ManifestSeasidePlotlyExamples class >> ruleRBUtilityMethodsRuleV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#'Seaside-Plotly-Examples')) #'2021-11-02T17:28:00.716211-03:00') )
]
